---
logging:

  buffered:
    size:
      size-value: 128000

  history:
    size: 10

  host:
    ipv4-host-list:

      APAC:
      - ipv4-host: 146.40.10.9
      - ipv4-host: 146.38.53.162

      US:
      - ipv4-host: 134.248.81.53
      - ipv4-host: 146.36.114.214

      EMEA:
      - ipv4-host: 134.248.81.53
      - ipv4-host: 146.38.53.162

  source-interface:
  - interface-name: mgmt_interface

